repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.9.0
    hooks:
    - id: commitizen
      stages:
      - commit-msg

  - repo: https://github.com/PyCQA/isort
    rev: 6.0.1
    hooks:
    - id: isort
      args:
      - --profile=black
      - --line-length=88

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
    - id: black
      args:
      - --line-length=88

  # flake8
  - repo: https://github.com/PyCQA/flake8
    rev: 7.3.0
    hooks:
    - id: flake8
      additional_dependencies:
        - flake8-docstrings
        - flake8-import-order
        - flake8-bugbear
      args:
      - "--max-line-length=88"
      - "--select=E,W,F,C,N,D"
      - "--ignore=E203,E501,W503"
      - "--exclude=.git,__pycache__,.tox,.eggs,*.egg,build,dist,.venv,venv,migrations"
      - "--per-file-ignores=__init__.py:F401,tests/*:D"

  # Others pre-commit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: check-merge-conflict
    - id: check-added-large-files
    - id: check-case-conflict
    - id: check-docstring-first
    - id: debug-statements

  - repo: https://github.com/PyCQA/autoflake
    rev: v2.3.1
    hooks:
    - id: autoflake
      args:
      - --remove-unused-variables
      - --remove-all-unused-imports
      - --in-place
      - --recursive

  - repo: https://github.com/python-poetry/poetry
    rev: 2.1.3
    hooks:
      - id: poetry-check

  # Security checks
  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.6
    hooks:
    - id: bandit
      args:
      - --skip=B101,B311,B324
      - --exclude=tests,migrations
      files: ^graphene_django_extras/

  # Type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.1
    hooks:
    - id: mypy
      additional_dependencies:
        - types-six
        - types-python-dateutil
      files: ^graphene_django_extras/
