name: Build

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Branch name to build'
        required: true
        type: string
      registry:
        description: 'Registry to push to'
        required: true
        default: dev
        type: choice
        options:
          - dev
          - prod

concurrency:
  group: ${{ github.workflow }}-${{ github.event.inputs.branch_name || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: runs-on=${{ github.run_id }}/runner=ubuntu
    if: github.event_name != 'workflow_dispatch' || (!contains(fromJSON('["develop", "release"]'), github.event.inputs.branch_name) && !contains(github.event.inputs.branch_name, 'v') && !contains(github.event.inputs.branch_name, '.x'))

    env:
      NX_RUNNER: release
      BRANCH_NAME: ${{ github.event.inputs.branch_name || github.ref_name }}
      DOCKER_REGISTRY: ${{ github.event.inputs.registry == 'dev' && vars.DOCKER_DEV_REGISTRY || vars.DOCKER_PROD_REGISTRY || 'docker.io' }}
      DOCKER_USERNAME: ${{ github.event.inputs.registry == 'dev' && vars.DOCKER_DEV_USERNAME || vars.DOCKER_PROD_USERNAME }}
      DOCKER_PASSWORD: ${{ github.event.inputs.registry == 'dev' && secrets.DOCKER_DEV_TOKEN || secrets.DOCKER_PROD_TOKEN }}
      DOCKER_IMAGE_NAME: powergauge

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ env.BRANCH_NAME }}

      - name: Log in to Docker registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}
          tags: |
            type=raw,value=${{ env.BRANCH_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            BRANCH_NAME=${{ env.BRANCH_NAME }}
          cache-from: type=gha,scope=${{ env.BRANCH_NAME }}
          cache-to: type=gha,mode=max,scope=${{ env.BRANCH_NAME }}